/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bbheader_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8d4cb9ffd681e83e2a59a7dc5d6bafa7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dvbgse/bbheader_source.h>
// pydoc.h is automatically generated in the build directory
#include <bbheader_source_pydoc.h>

void bind_bbheader_source(py::module& m)
{

    using bbheader_source    = ::gr::dvbgse::bbheader_source;


    py::class_<bbheader_source, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<bbheader_source>>(m, "bbheader_source", D(bbheader_source))

        .def(py::init(&bbheader_source::make),
           py::arg("standard"),
           py::arg("framesize"),
           py::arg("rate"),
           py::arg("rolloff"),
           py::arg("inband"),
           py::arg("fecblocks"),
           py::arg("tsrate"),
           py::arg("ping_reply"),
           py::arg("ipaddr_spoof"),
           py::arg("src_address"),
           py::arg("dst_address"),
           py::arg("padding_len"),
           D(bbheader_source,make)
        )
        



        ;




}








