/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bbheader_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(03ac7752aecbfdd8341a8da486b01fe5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dvbgse/bbheader_sink.h>
// pydoc.h is automatically generated in the build directory
#include <bbheader_sink_pydoc.h>

void bind_bbheader_sink(py::module& m)
{

    using bbheader_sink    = ::gr::dvbgse::bbheader_sink;


    py::class_<bbheader_sink, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<bbheader_sink>>(m, "bbheader_sink", D(bbheader_sink))

        .def(py::init(&bbheader_sink::make),
           py::arg("standard"),
           py::arg("framesize"),
           py::arg("rate"),
           D(bbheader_sink,make)
        )
        



        ;




}








